# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Calendar(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, appointment: List[object]=None):  # noqa: E501
        """Calendar - a model defined in Swagger

        :param appointment: The appointment of this Calendar.  # noqa: E501
        :type appointment: List[object]
        """
        self.swagger_types = {
            'appointment': List[object]
        }

        self.attribute_map = {
            'appointment': 'Appointment'
        }

        self._appointment = appointment

    @classmethod
    def from_dict(cls, dikt) -> 'Calendar':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Calendar of this Calendar.  # noqa: E501
        :rtype: Calendar
        """
        return util.deserialize_model(dikt, cls)

    @property
    def appointment(self) -> List[object]:
        """Gets the appointment of this Calendar.


        :return: The appointment of this Calendar.
        :rtype: List[object]
        """
        return self._appointment

    @appointment.setter
    def appointment(self, appointment: List[object]):
        """Sets the appointment of this Calendar.


        :param appointment: The appointment of this Calendar.
        :type appointment: List[object]
        """

        self._appointment = appointment
